### ISSUE TITLE
Hero App Completion Auslin

### ISSUE THREAD

**Issue by salatematha** [DaisyPradhisha/StockAid#3]
Separate repository

**Comment by AuslinPJ** [comment]
completed hero editor & master detail

**Comment by salatematha** [comment]
Auslin Did you create a separate repository for your heroes sample App? If you have created pls send us all the link to the repository. like eg Pradhisha's repository link is https://github.com/DaisyPradhisha/A-Rookies-Heroes-Stock-app

**Comment by AuslinPJ** [comment]
https://github.com/AuslinPJ/creative-heroes.git

**Comment by AuslinPJ** [comment]
completed multiple components & services

**Comment by AuslinPJ** [comment]
completed routing

**Comment by AuslinPJ** [comment]
completed http

**Comment by AuslinPJ** [comment]
studied autocomplete, line chart deploying with simple examples. 
https://github.com/AuslinPJ/simplelinechart
Included a simple autocomplete code in herodetails
