### ISSUE TITLE
Hero App Completion Pradhisha

### ISSUE THREAD

**Issue by salatematha** [DaisyPradhisha/StockAid#4]

**Comment by DaisyPradhisha** [comment]
### Completed the hero editor part

**Comment by DaisyPradhisha** [comment]
Completed Master/Detail part.

**Comment by DaisyPradhisha** [comment]
Completed Multiple Components.

**Comment by DaisyPradhisha** [comment]
Currently unable to push the new code . Getting the error message 

_> git push
> fatal: unable to access 'https://github.com/DaisyPradhisha/A-Rookies-Heroes-Stock-app.git/': Could not resolve host: github.com_

Working on it .

**Comment by DaisyPradhisha** [comment]
### Bug fixed.

**Comment by DaisyPradhisha** [comment]
Completed Services.

**Comment by DaisyPradhisha** [comment]
Completed Routing.
