### ISSUE TITLE
Angular Material

### ISSUE THREAD

**Issue by salatematha** [DaisyPradhisha/StockAid#7]
For all components except chart and also data table

**Comment by DaisyPradhisha** [comment]
I am trying to "import {MdAutocompleteModule} from '@angular/material';"
but getting this error " can not find module “@angular/material”". 
Can I get some help to fix this ?

**Comment by DaisyPradhisha** [comment]
I am trying to import {MdAutocompleteModule} from '@angular/material';

but getting this error " can not find module @angular/material.
Can I get some help to fix this ?

**Comment by DaisyPradhisha** [comment]
I am trying to import {MdAutocompleteModule} from angular/material
but getting this error  can not find module angular/material.
Can I get some help to fix this ?

**Comment by DaisyPradhisha** [comment]
Angular/material was not installed . Installed it now .Problem solved for now.

**Comment by salatematha** [comment]
Just saw the message. thats great you installed angular material also

**Comment by DaisyPradhisha** [comment]
Studied angular material and  merged autocomplete in heroes app.
